apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-client-config-tpl
  namespace: polaris-system
data:
  polaris.yaml: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      namespace: {{ .Namespace }}
      name: {{ .Name }}
    data:
      polaris.yaml: |-
        global:
          serverConnector:
            addresses:
              - {{ .PolarisServer }}
          statReporter:
            enable: true
            chain:
            - prometheus
            plugin:
              prometheus:
                metricPort: 0
