## polaris controller
## Ref:https://github.com/polarismesh/polaris-controller/blob/main/README.md

## Overrides for generated resource names
# See templates/_helpers.tpl
# nameOverride:
# fullnameOverride:

## cluster name register in polaris server
cluster:
  name: default

## sidecar config for controller injector
sidecar:
  port: 443
  mode: mesh
  image:
    repo: polarismesh/polaris-sidecar
    tag: #SIDECAR_VERSION#
    pullPolicy: Always
  init:
    image:
      repo: polarismesh/polaris-sidecar-init
      tag: #CONTROLLER_VERSION#
      pullPolicy: Always
  envoy:
    image:
      repo: envoyproxy/envoy
      tag: #ENVOY_VERSION#
  envoy_builder:
    image:
      repo: polarismesh/polaris-envoy-bootstrap-generator
      tag: #CONTROLLER_VERSION#

## polaris server config
polaris:
  server:
    address: #POLARIS_HOST#
    token: #POLARIS_TOKEN#
    operator: #POLARIS_OPERATOR#
  sync:
    service:
      mode: all
    config:
      enable: true
      direction: both
      groupName: default
      allowDelete: false


## polaris controller config
controller:
  name: polaris-controller
  webhook:
    host: polaris.tencent.com
    service: polaris-sidecar-injector
  image:
    repo: polarismesh/polaris-controller
    tag: #CONTROLLER_VERSION#
    pullPolicy: IfNotPresent
  limit:
    cpu: 2
    memory: 2Gi
  metrics:
    port: 80
    type: ClusterIP
