apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polaris-controller.controller.fullname" . }}-mesh
  namespace: polaris-system
data:
  mesh: |-
    logger:
      default:
        rotateOutputPath: logs/polaris-default.log
        errorRotateOutputPath: logs/polaris-default-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      synccm:
        rotateOutputPath: logs/polaris-synccm.log
        errorRotateOutputPath: logs/polaris-synccm-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      syncnaming:
        rotateOutputPath: logs/polaris-syncnaming.log
        errorRotateOutputPath: logs/polaris-syncnaming-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      syncconfig:
        rotateOutputPath: logs/polaris-syncconfig.log
        errorRotateOutputPath: logs/polaris-syncconfig-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      inject:
        rotateOutputPath: logs/polaris-inject.log
        errorRotateOutputPath: logs/polaris-inject-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
    # k8s cluster name
    clusterName: "{{ .Values.cluster.name }}"
    # polaris-sidecar 注入的默认启动模式, 可以配置 mesh 或者 dns
    sidecarInject:
      mode: "{{ .Values.sidecar.mesh }}"
    # service sync
    serviceSync:
      mode: {{ .Values.polaris.sync.service.mode }}
      serverAddress: {{ .Values.polaris.server.address }}
      # 北极星开启鉴权时需要配置
      accessToken: {{ .Values.polaris.server.token }}
    configSync:
      enable: {{ .Values.polaris.sync.config.enable }}
      serverAddress: {{ .Values.polaris.server.address }}
      # 北极星开启鉴权时需要配置
      accessToken: {{ .Values.polaris.server.token }}
      allowDelete: {{ .Values.polaris.sync.config.allowDelete }}
      # 配置同步方向: kubernetesToPolaris|polarisToKubernetes|both
      syncDirection: {{ .Values.polaris.sync.config.direction }}
      defaultGroup: {{ .Values.polaris.sync.config.groupName }}
    defaultConfig:
      proxyMetadata:
        serverAddress: {{ .Values.polaris.server.address }}
        clusterName: "{{ .Values.cluster.name }}"
