apiVersion: v1
appVersion: v1.3.0
description: Polaris controller for Kubernetes is used to synchronize endpoints to polaris and inject sidecars into business pods
home: https://github.com/polarismesh/polaris-controller
icon: https://avatars.githubusercontent.com/u/85474408?s=200&v=4
keywords:
- controller
- polaris
maintainers:
- name: jlongzhou@tencent.com
name: polaris-controller
sources:
- https://github.com/polarismesh/polaris-controller
version: 1.3.0
